In [28]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import StackingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import seaborn as sns
from sklearn.linear_model import LogisticRegression

In [29]:
df=sns.load_dataset('iris')

In [30]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [31]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [32]:
X= df.drop('species',axis=1)
y=df['species']

In [33]:
from sklearn.preprocessing import LabelEncoder

In [34]:
le= LabelEncoder()
y_encode= le.fit_transform(y)

In [35]:
X_train,X_test,y_train,y_test = train_test_split(X,y_encode,test_size=0.20,random_state=42,stratify=y_encode)

In [36]:
base_learners=[
    ('dt',DecisionTreeClassifier(random_state=42)),
    ('svc',SVC(probability=True,kernel='rbf',random_state=42)),
    ('lr',LogisticRegression(max_iter=1000))
]

In [37]:
meta_learner = LogisticRegression(max_iter=1000)

In [38]:
stacking_clf = StackingClassifier(estimators=base_learners,final_estimator=meta_learner,cv=5)