In [1]:
import pandas as pd

In [2]:
pd.__version__

'3.0.5'

In [3]:
# create Dataframe

df = pd.DataFrame([11,12,13],columns=['name'])
print(df)

   name
0    11
1    12
2    13

In [4]:
print(type(df))

<class 'pandas.DataFrame'>

In [5]:
data = {
    'name':['biplob','ram','hari','krishna'],
    'age':[23,80,40,10],
    'salary':[34000,70000,50000,100000]
}

In [6]:
df = pd.DataFrame(data)
print(df)

      name  age  salary
0   biplob   23   34000
1      ram   80   70000
2     hari   40   50000
3  krishna   10  100000

In [7]:
# Basic DataFrame understanding

df.head()

      name  age  salary
0   biplob   23   34000
1      ram   80   70000
2     hari   40   50000
3  krishna   10  100000

In [8]:
df.tail(2)

      name  age  salary
2     hari   40   50000
3  krishna   10  100000

In [9]:
df.shape

(4, 3)

In [10]:
df.columns

Index(['name', 'age', 'salary'], dtype='str')

In [11]:
changed_df=df.rename(columns={"name":"Name","age":"Age","salary":"Montlhy_Salary"},inplace=True)

In [12]:
df

      Name  Age  Montlhy_Salary
0   biplob   23           34000
1      ram   80           70000
2     hari   40           50000
3  krishna   10          100000

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      str
 1   Age             4 non-null      int64
 2   Montlhy_Salary  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [14]:
df.describe()

             Age  Montlhy_Salary
count   4.000000        4.000000
mean   38.250000    63500.000000
std    30.423401    28442.925307
min    10.000000    34000.000000
25%    19.750000    46000.000000
50%    31.500000    60000.000000
75%    50.000000    77500.000000
max    80.000000   100000.000000

In [15]:
# Save and Load data from csv
df.to_csv('test_value.csv',index=False)

In [16]:
load_df = pd.read_csv('test_value.csv')
load_df

      Name  Age  Montlhy_Salary
0   biplob   23           34000
1      ram   80           70000
2     hari   40           50000
3  krishna   10          100000

In [17]:
# select column

df[['Name']]

      Name
0   biplob
1      ram
2     hari
3  krishna

In [18]:
df[['Name','Age']]

      Name  Age
0   biplob   23
1      ram   80
2     hari   40
3  krishna   10

In [19]:
# select rows
# loc = indexx name baased
df.loc[df.Name=='biplob']
df.loc[(df.Name=='biplob') & (df.Montlhy_Salary >=40000)]

Empty DataFrame
Columns: [Name, Age, Montlhy_Salary]
Index: []

In [20]:
# iloc -- index value based
df.iloc[0:2]

     Name  Age  Montlhy_Salary
0  biplob   23           34000
1     ram   80           70000

In [21]:
# filter df
df

      Name  Age  Montlhy_Salary
0   biplob   23           34000
1      ram   80           70000
2     hari   40           50000
3  krishna   10          100000

In [22]:
df[(df['Age']>24) & (df['Montlhy_Salary']>=55000)]

  Name  Age  Montlhy_Salary
1  ram   80           70000

In [23]:
df.where(df['Age']>=25,other='Not Eligible')

           Name           Age Montlhy_Salary
0  Not Eligible  Not Eligible   Not Eligible
1           ram            80          70000
2          hari            40          50000
3  Not Eligible  Not Eligible   Not Eligible

In [24]:
df

      Name  Age  Montlhy_Salary
0   biplob   23           34000
1      ram   80           70000
2     hari   40           50000
3  krishna   10          100000

In [25]:
# add new column

df['Team']=['DA','HR','CTO','CEO']

In [26]:
df

      Name  Age  Montlhy_Salary Team
0   biplob   23           34000   DA
1      ram   80           70000   HR
2     hari   40           50000  CTO
3  krishna   10          100000  CEO

In [27]:
df['Bonus']= df['Montlhy_Salary']*0.2
df

      Name  Age  Montlhy_Salary Team    Bonus
0   biplob   23           34000   DA   6800.0
1      ram   80           70000   HR  14000.0
2     hari   40           50000  CTO  10000.0
3  krishna   10          100000  CEO  20000.0

In [28]:
# add new rows
df.loc[len(df)] =['Shiva','81','115000','chairman','25000']

In [29]:
df

      Name Age Montlhy_Salary      Team    Bonus
0   biplob  23          34000        DA   6800.0
1      ram  80          70000        HR  14000.0
2     hari  40          50000       CTO  10000.0
3  krishna  10         100000       CEO  20000.0
4    Shiva  81         115000  chairman    25000

In [30]:
len(df)

5

In [31]:
# update value
df.loc[3, 'Age'] = 50
df

      Name Age Montlhy_Salary      Team    Bonus
0   biplob  23          34000        DA   6800.0
1      ram  80          70000        HR  14000.0
2     hari  40          50000       CTO  10000.0
3  krishna  50         100000       CEO  20000.0
4    Shiva  81         115000  chairman    25000

In [32]:
# update value using column name

df.loc[df.Name =='ram','Age']=60

In [33]:
df

      Name Age Montlhy_Salary      Team    Bonus
0   biplob  23          34000        DA   6800.0
1      ram  60          70000        HR  14000.0
2     hari  40          50000       CTO  10000.0
3  krishna  50         100000       CEO  20000.0
4    Shiva  81         115000  chairman    25000

In [34]:
# delete value row and column values

df.drop(df[df.Name== 'biplob'].index,inplace=True) #drop row axis = 0

In [35]:
df.drop('Bonus',axis=1,inplace=True)

In [36]:
df

      Name Age Montlhy_Salary      Team
1      ram  60          70000        HR
2     hari  40          50000       CTO
3  krishna  50         100000       CEO
4    Shiva  81         115000  chairman

In [37]:
print(type(df['Age']))

<class 'pandas.Series'>

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 1 to 4
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      str
 1   Age             4 non-null      object
 2   Montlhy_Salary  4 non-null      object
 3   Team            4 non-null      str
dtypes: object(2), str(2)
memory usage: 260.0+ bytes

In [39]:
# Sorting value
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')

df = df.sort_values('Age', ascending=False)

In [40]:
df

      Name  Age Montlhy_Salary      Team
4    Shiva   81         115000  chairman
1      ram   60          70000        HR
3  krishna   50         100000       CEO
2     hari   40          50000       CTO

In [41]:
# Working with datetime values
df['DOJ']=['2023-01-01','2024-01-10','2024-02-12','2024-10-12']
df

      Name  Age Montlhy_Salary      Team         DOJ
4    Shiva   81         115000  chairman  2023-01-01
1      ram   60          70000        HR  2024-01-10
3  krishna   50         100000       CEO  2024-02-12
2     hari   40          50000       CTO  2024-10-12

In [42]:
df['DOJ'].dtype

In [43]:
df['DOJ'] = pd.to_datetime(df['DOJ'])

In [44]:
df.dtypes

Name                         str
Age                        int64
Montlhy_Salary            object
Team                         str
DOJ               datetime64[us]
dtype: object

In [45]:
df1=df['DOJ2']=['01-01-2023','12-01-2024','02-12-2024','18-02-2024']

In [46]:
df1=df

In [47]:
df1

      Name  Age Montlhy_Salary      Team        DOJ        DOJ2
4    Shiva   81         115000  chairman 2023-01-01  01-01-2023
1      ram   60          70000        HR 2024-01-10  12-01-2024
3  krishna   50         100000       CEO 2024-02-12  02-12-2024
2     hari   40          50000       CTO 2024-10-12  18-02-2024

In [48]:
df1['DOJ2'].dtypes

In [49]:
df1['DOJ2']=pd.to_datetime(df['DOJ2'],format='%d-%m-%Y')

In [50]:
df1['DOJ2'].dtypes

dtype('<M8[us]')

In [51]:
df1

      Name  Age Montlhy_Salary      Team        DOJ       DOJ2
4    Shiva   81         115000  chairman 2023-01-01 2023-01-01
1      ram   60          70000        HR 2024-01-10 2024-01-12
3  krishna   50         100000       CEO 2024-02-12 2024-12-02
2     hari   40          50000       CTO 2024-10-12 2024-02-18

In [52]:
df.drop('DOJ2',inplace=True,axis=1)
df

      Name  Age Montlhy_Salary      Team        DOJ
4    Shiva   81         115000  chairman 2023-01-01
1      ram   60          70000        HR 2024-01-10
3  krishna   50         100000       CEO 2024-02-12
2     hari   40          50000       CTO 2024-10-12

In [53]:
df['DOJ'].dt.year

4    2023
1    2024
3    2024
2    2024
Name: DOJ, dtype: int32

In [54]:
print('month:',df['DOJ'].dt.month)
print('day:',df['DOJ'].dt.day)

month: 4     1
1     1
3     2
2    10
Name: DOJ, dtype: int32
day: 4     1
1    10
3    12
2    12
Name: DOJ, dtype: int32

In [55]:
import numpy as np

In [56]:
df.loc[df.Name =='hari','Montlhy_Salary']=np.nan

In [57]:
df

      Name  Age Montlhy_Salary      Team        DOJ
4    Shiva   81         115000  chairman 2023-01-01
1      ram   60          70000        HR 2024-01-10
3  krishna   50         100000       CEO 2024-02-12
2     hari   40            NaN       CTO 2024-10-12

In [58]:
df.isnull()

    Name    Age  Montlhy_Salary   Team    DOJ
4  False  False           False  False  False
1  False  False           False  False  False
3  False  False           False  False  False
2  False  False            True  False  False

In [59]:
df.isnull().sum()

Name              0
Age               0
Montlhy_Salary    1
Team              0
DOJ               0
dtype: int64

In [60]:
df.fillna(0)

      Name  Age Montlhy_Salary      Team        DOJ
4    Shiva   81         115000  chairman 2023-01-01
1      ram   60          70000        HR 2024-01-10
3  krishna   50         100000       CEO 2024-02-12
2     hari   40              0       CTO 2024-10-12

In [61]:
df

      Name  Age Montlhy_Salary      Team        DOJ
4    Shiva   81         115000  chairman 2023-01-01
1      ram   60          70000        HR 2024-01-10
3  krishna   50         100000       CEO 2024-02-12
2     hari   40            NaN       CTO 2024-10-12

In [62]:
df.loc[df['Name']=='hari','Montlhy_Salary']=50000

In [63]:
df

      Name  Age Montlhy_Salary      Team        DOJ
4    Shiva   81         115000  chairman 2023-01-01
1      ram   60          70000        HR 2024-01-10
3  krishna   50         100000       CEO 2024-02-12
2     hari   40          50000       CTO 2024-10-12

In [64]:
df

      Name  Age Montlhy_Salary      Team        DOJ
4    Shiva   81         115000  chairman 2023-01-01
1      ram   60          70000        HR 2024-01-10
3  krishna   50         100000       CEO 2024-02-12
2     hari   40          50000       CTO 2024-10-12

In [65]:
df.rename(columns={'Montlhy_Salary':'Monthly_Salary'})

      Name  Age Monthly_Salary      Team        DOJ
4    Shiva   81         115000  chairman 2023-01-01
1      ram   60          70000        HR 2024-01-10
3  krishna   50         100000       CEO 2024-02-12
2     hari   40          50000       CTO 2024-10-12

In [66]:
df.loc[df['Name'] == 'Shiva', 'Monthly_Salary'] = 115000
df.loc[df['Name'] == 'ram', 'Monthly_Salary'] = 80000
df.loc[df['Name'] == 'krishna', 'Monthly_Salary'] = 60000

In [67]:
df

      Name  Age Montlhy_Salary      Team        DOJ  Monthly_Salary
4    Shiva   81         115000  chairman 2023-01-01        115000.0
1      ram   60          70000        HR 2024-01-10         80000.0
3  krishna   50         100000       CEO 2024-02-12         60000.0
2     hari   40          50000       CTO 2024-10-12             NaN

In [68]:
df.drop('Monthly_Salary',axis=1)

      Name  Age Montlhy_Salary      Team        DOJ
4    Shiva   81         115000  chairman 2023-01-01
1      ram   60          70000        HR 2024-01-10
3  krishna   50         100000       CEO 2024-02-12
2     hari   40          50000       CTO 2024-10-12

In [69]:
df.rename(columns={'Montlhy_Salary':'Monthly_salary'},inplace=True)
df

      Name  Age Monthly_salary      Team        DOJ  Monthly_Salary
4    Shiva   81         115000  chairman 2023-01-01        115000.0
1      ram   60          70000        HR 2024-01-10         80000.0
3  krishna   50         100000       CEO 2024-02-12         60000.0
2     hari   40          50000       CTO 2024-10-12             NaN

In [70]:
df.drop('Monthly_Salary',axis=1,inplace=True)

In [71]:
df

      Name  Age Monthly_salary      Team        DOJ
4    Shiva   81         115000  chairman 2023-01-01
1      ram   60          70000        HR 2024-01-10
3  krishna   50         100000       CEO 2024-02-12
2     hari   40          50000       CTO 2024-10-12