In [85]:
import pandas as pd

In [86]:
pd.__version__

'3.0.5'

In [87]:
# create Dataframe

df = pd.DataFrame([11,12,13],columns=['name'])
print(df)

   name
0    11
1    12
2    13

In [88]:
print(type(df))

<class 'pandas.DataFrame'>

In [89]:
data = {
    'name':['biplob','ram','hari','krishna'],
    'age':[23,80,40,10],
    'salary':[34000,70000,50000,100000]
}

In [90]:
df = pd.DataFrame(data)
print(df)

      name  age  salary
0   biplob   23   34000
1      ram   80   70000
2     hari   40   50000
3  krishna   10  100000

In [91]:
# Basic DataFrame understanding

df.head()

      name  age  salary
0   biplob   23   34000
1      ram   80   70000
2     hari   40   50000
3  krishna   10  100000

In [92]:
df.tail(2)

      name  age  salary
2     hari   40   50000
3  krishna   10  100000

In [93]:
df.shape

(4, 3)

In [94]:
df.columns

Index(['name', 'age', 'salary'], dtype='str')

In [95]:
changed_df=df.rename(columns={"name":"Name","age":"Age","salary":"Montlhy_Salary"},inplace=True)

In [96]:
df

      Name  Age  Montlhy_Salary
0   biplob   23           34000
1      ram   80           70000
2     hari   40           50000
3  krishna   10          100000

In [97]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      str
 1   Age             4 non-null      int64
 2   Montlhy_Salary  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [98]:
df.describe()

             Age  Montlhy_Salary
count   4.000000        4.000000
mean   38.250000    63500.000000
std    30.423401    28442.925307
min    10.000000    34000.000000
25%    19.750000    46000.000000
50%    31.500000    60000.000000
75%    50.000000    77500.000000
max    80.000000   100000.000000

In [99]:
# Save and Load data from csv
df.to_csv('test_value.csv',index=False)

In [100]:
load_df = pd.read_csv('test_value.csv')
load_df

      Name  Age  Montlhy_Salary
0   biplob   23           34000
1      ram   80           70000
2     hari   40           50000
3  krishna   10          100000

In [101]:
# select column

df[['Name']]

      Name
0   biplob
1      ram
2     hari
3  krishna

In [102]:
df[['Name','Age']]

      Name  Age
0   biplob   23
1      ram   80
2     hari   40
3  krishna   10

In [103]:
# select rows
# loc = indexx name baased
df.loc[df.Name=='biplob']
df.loc[(df.Name=='biplob') & (df.Montlhy_Salary >=40000)]

Empty DataFrame
Columns: [Name, Age, Montlhy_Salary]
Index: []

In [104]:
# iloc -- index value based
df.iloc[0:2]

     Name  Age  Montlhy_Salary
0  biplob   23           34000
1     ram   80           70000

In [105]:
# filter df
df

      Name  Age  Montlhy_Salary
0   biplob   23           34000
1      ram   80           70000
2     hari   40           50000
3  krishna   10          100000

In [106]:
df[(df['Age']>24) & (df['Montlhy_Salary']>=55000)]

  Name  Age  Montlhy_Salary
1  ram   80           70000

In [107]:
df.where(df['Age']>=25,other='Not Eligible')

           Name           Age Montlhy_Salary
0  Not Eligible  Not Eligible   Not Eligible
1           ram            80          70000
2          hari            40          50000
3  Not Eligible  Not Eligible   Not Eligible

In [108]:
df

      Name  Age  Montlhy_Salary
0   biplob   23           34000
1      ram   80           70000
2     hari   40           50000
3  krishna   10          100000

In [109]:
# add new column

df['Team']=['DA','HR','CTO','CEO']

In [110]:
df

      Name  Age  Montlhy_Salary Team
0   biplob   23           34000   DA
1      ram   80           70000   HR
2     hari   40           50000  CTO
3  krishna   10          100000  CEO

In [111]:
df['Bonus']= df['Montlhy_Salary']*0.2
df

      Name  Age  Montlhy_Salary Team    Bonus
0   biplob   23           34000   DA   6800.0
1      ram   80           70000   HR  14000.0
2     hari   40           50000  CTO  10000.0
3  krishna   10          100000  CEO  20000.0

In [112]:
# add new rows
df.loc[len(df)] =['Shiva','81','115000','chairman','25000']

In [113]:
df

      Name Age Montlhy_Salary      Team    Bonus
0   biplob  23          34000        DA   6800.0
1      ram  80          70000        HR  14000.0
2     hari  40          50000       CTO  10000.0
3  krishna  10         100000       CEO  20000.0
4    Shiva  81         115000  chairman    25000

In [114]:
len(df)

5

In [115]:
# update value
df.loc[3, 'Age'] = 50
df

      Name Age Montlhy_Salary      Team    Bonus
0   biplob  23          34000        DA   6800.0
1      ram  80          70000        HR  14000.0
2     hari  40          50000       CTO  10000.0
3  krishna  50         100000       CEO  20000.0
4    Shiva  81         115000  chairman    25000

In [116]:
# update value using column name

df.loc[df.Name =='ram','Age']=60

In [117]:
df

      Name Age Montlhy_Salary      Team    Bonus
0   biplob  23          34000        DA   6800.0
1      ram  60          70000        HR  14000.0
2     hari  40          50000       CTO  10000.0
3  krishna  50         100000       CEO  20000.0
4    Shiva  81         115000  chairman    25000

In [118]:
# delete value row and column values

df.drop(df[df.Name== 'biplob'].index,inplace=True) #drop row axis = 0

In [119]:
df.drop('Bonus',axis=1,inplace=True)

In [120]:
df

      Name Age Montlhy_Salary      Team
1      ram  60          70000        HR
2     hari  40          50000       CTO
3  krishna  50         100000       CEO
4    Shiva  81         115000  chairman

In [121]:
print(type(df['Age']))

<class 'pandas.Series'>

In [122]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 1 to 4
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      str
 1   Age             4 non-null      object
 2   Montlhy_Salary  4 non-null      object
 3   Team            4 non-null      str
dtypes: object(2), str(2)
memory usage: 260.0+ bytes

In [123]:
# Sorting value
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')

df = df.sort_values('Age', ascending=False)

In [124]:
df

      Name  Age Montlhy_Salary      Team
4    Shiva   81         115000  chairman
1      ram   60          70000        HR
3  krishna   50         100000       CEO
2     hari   40          50000       CTO

In [125]:
# Working with datetime values
df['DOJ']=['2023-01-01','2024-01-10','2024-02-12','2024-10-12']
df

      Name  Age Montlhy_Salary      Team         DOJ
4    Shiva   81         115000  chairman  2023-01-01
1      ram   60          70000        HR  2024-01-10
3  krishna   50         100000       CEO  2024-02-12
2     hari   40          50000       CTO  2024-10-12

In [126]:
df['DOJ'].dtype

In [127]:
df['DOJ'] = pd.to_datetime(df['DOJ'])

In [128]:
df.dtypes

Name                         str
Age                        int64
Montlhy_Salary            object
Team                         str
DOJ               datetime64[us]
dtype: object

In [129]:
df1=df['DOJ2']=['01-01-2023','12-01-2024','02-12-2024','18-02-2024']

In [130]:
df1=df

In [131]:
df1

      Name  Age Montlhy_Salary      Team        DOJ        DOJ2
4    Shiva   81         115000  chairman 2023-01-01  01-01-2023
1      ram   60          70000        HR 2024-01-10  12-01-2024
3  krishna   50         100000       CEO 2024-02-12  02-12-2024
2     hari   40          50000       CTO 2024-10-12  18-02-2024

In [132]:
df1['DOJ2'].dtypes

In [133]:
df1['DOJ2']=pd.to_datetime(df['DOJ2'],format='%d-%m-%Y')

In [134]:
df1['DOJ2'].dtypes

dtype('<M8[us]')

In [135]:
df1

      Name  Age Montlhy_Salary      Team        DOJ       DOJ2
4    Shiva   81         115000  chairman 2023-01-01 2023-01-01
1      ram   60          70000        HR 2024-01-10 2024-01-12
3  krishna   50         100000       CEO 2024-02-12 2024-12-02
2     hari   40          50000       CTO 2024-10-12 2024-02-18

In [136]:
df.drop('DOJ2',inplace=True,axis=1)
df

      Name  Age Montlhy_Salary      Team        DOJ
4    Shiva   81         115000  chairman 2023-01-01
1      ram   60          70000        HR 2024-01-10
3  krishna   50         100000       CEO 2024-02-12
2     hari   40          50000       CTO 2024-10-12

In [137]:
df['DOJ'].dt.year

4    2023
1    2024
3    2024
2    2024
Name: DOJ, dtype: int32

In [138]:
print('month:',df['DOJ'].dt.month)
print('day:',df['DOJ'].dt.day)

month: 4     1
1     1
3     2
2    10
Name: DOJ, dtype: int32
day: 4     1
1    10
3    12
2    12
Name: DOJ, dtype: int32

In [139]:
import numpy as np

In [140]:
df.loc[df.Name =='hari','Montlhy_Salary']=np.nan

In [141]:
df

      Name  Age Montlhy_Salary      Team        DOJ
4    Shiva   81         115000  chairman 2023-01-01
1      ram   60          70000        HR 2024-01-10
3  krishna   50         100000       CEO 2024-02-12
2     hari   40            NaN       CTO 2024-10-12

In [142]:
df.isnull()

    Name    Age  Montlhy_Salary   Team    DOJ
4  False  False           False  False  False
1  False  False           False  False  False
3  False  False           False  False  False
2  False  False            True  False  False

In [143]:
df.isnull().sum()

Name              0
Age               0
Montlhy_Salary    1
Team              0
DOJ               0
dtype: int64

In [144]:
df.fillna(0)

      Name  Age Montlhy_Salary      Team        DOJ
4    Shiva   81         115000  chairman 2023-01-01
1      ram   60          70000        HR 2024-01-10
3  krishna   50         100000       CEO 2024-02-12
2     hari   40              0       CTO 2024-10-12

In [145]:
df

      Name  Age Montlhy_Salary      Team        DOJ
4    Shiva   81         115000  chairman 2023-01-01
1      ram   60          70000        HR 2024-01-10
3  krishna   50         100000       CEO 2024-02-12
2     hari   40            NaN       CTO 2024-10-12

In [146]:
df.loc[df['Name']=='hari','Montlhy_Salary']=50000

In [147]:
df

      Name  Age Montlhy_Salary      Team        DOJ
4    Shiva   81         115000  chairman 2023-01-01
1      ram   60          70000        HR 2024-01-10
3  krishna   50         100000       CEO 2024-02-12
2     hari   40          50000       CTO 2024-10-12

In [148]:
df

      Name  Age Montlhy_Salary      Team        DOJ
4    Shiva   81         115000  chairman 2023-01-01
1      ram   60          70000        HR 2024-01-10
3  krishna   50         100000       CEO 2024-02-12
2     hari   40          50000       CTO 2024-10-12

In [149]:
df.rename(columns={'Montlhy_Salary':'Monthly_Salary'})

      Name  Age Monthly_Salary      Team        DOJ
4    Shiva   81         115000  chairman 2023-01-01
1      ram   60          70000        HR 2024-01-10
3  krishna   50         100000       CEO 2024-02-12
2     hari   40          50000       CTO 2024-10-12

In [150]:
df.loc[df['Name'] == 'Shiva', 'Monthly_Salary'] = 115000
df.loc[df['Name'] == 'ram', 'Monthly_Salary'] = 80000
df.loc[df['Name'] == 'krishna', 'Monthly_Salary'] = 60000

In [151]:
df

      Name  Age Montlhy_Salary      Team        DOJ  Monthly_Salary
4    Shiva   81         115000  chairman 2023-01-01        115000.0
1      ram   60          70000        HR 2024-01-10         80000.0
3  krishna   50         100000       CEO 2024-02-12         60000.0
2     hari   40          50000       CTO 2024-10-12             NaN

In [152]:
df.drop('Monthly_Salary',axis=1)

      Name  Age Montlhy_Salary      Team        DOJ
4    Shiva   81         115000  chairman 2023-01-01
1      ram   60          70000        HR 2024-01-10
3  krishna   50         100000       CEO 2024-02-12
2     hari   40          50000       CTO 2024-10-12

In [153]:
df.rename(columns={'Montlhy_Salary':'Monthly_salary'},inplace=True)
df

      Name  Age Monthly_salary      Team        DOJ  Monthly_Salary
4    Shiva   81         115000  chairman 2023-01-01        115000.0
1      ram   60          70000        HR 2024-01-10         80000.0
3  krishna   50         100000       CEO 2024-02-12         60000.0
2     hari   40          50000       CTO 2024-10-12             NaN

In [154]:
df.drop('Monthly_Salary',axis=1,inplace=True)

In [155]:
df

      Name  Age Monthly_salary      Team        DOJ
4    Shiva   81         115000  chairman 2023-01-01
1      ram   60          70000        HR 2024-01-10
3  krishna   50         100000       CEO 2024-02-12
2     hari   40          50000       CTO 2024-10-12

In [156]:
# Aggregation and groupby
df['Team'].value_counts()

Team
chairman    1
HR          1
CEO         1
CTO         1
Name: count, dtype: int64

In [157]:
df[df['Team']=='CEO'].value_counts()

Name     Age  Monthly_salary  Team  DOJ
krishna  50   100000          CEO   2024-02-12    1
Name: count, dtype: int64

In [158]:
df.groupby('Team')['Monthly_salary'].sum() #Aggregation based on groupby

Team
CEO         100000
CTO          50000
HR           70000
chairman    115000
Name: Monthly_salary, dtype: object

In [159]:
df.groupby('Team').agg({'Monthly_salary':'size','Name':'count'})

          Monthly_salary  Name
Team
CEO                    1     1
CTO                    1     1
HR                     1     1
chairman               1     1

In [160]:
# Concatenate and merge datasets
df1= pd.DataFrame({'ID':[1,2,3],'Name':['A','B','C']})
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [163]:
df2= pd.DataFrame({'ID':[1,2,3,4],'Score':[88,23,76,98]})
df2

   ID  Score
0   1     88
1   2     23
2   3     76
3   4     98

In [ ]:
pd.concat([df1,df2],axis=0) # vertical , row level, top on top

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   88.0
1   2  NaN   23.0
2   3  NaN   76.0
3   4  NaN   98.0

In [166]:
pd.concat([df1,df2],axis=1) # horizontal,column level,side on side

    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     23
2  3.0    C   3     76
3  NaN  NaN   4     98

In [167]:
#  merge = join
pd.merge(df1,df2,how='inner',on='ID')

   ID Name  Score
0   1    A     88
1   2    B     23
2   3    C     76

In [168]:
pd.merge(df1,df2, how='inner',left_on='ID',right_on='ID')

   ID Name  Score
0   1    A     88
1   2    B     23
2   3    C     76