In [57]:
import pandas as pd

In [58]:
pd.__version__

'3.0.5'

In [59]:
# create Dataframe

df = pd.DataFrame([11,12,13],columns=['name'])
print(df)

   name
0    11
1    12
2    13

In [60]:
print(type(df))

<class 'pandas.DataFrame'>

In [61]:
data = {
    'name':['biplob','ram','hari','krishna'],
    'age':[23,80,40,10],
    'salary':[34000,70000,50000,100000]
}

In [62]:
df = pd.DataFrame(data)
print(df)

      name  age  salary
0   biplob   23   34000
1      ram   80   70000
2     hari   40   50000
3  krishna   10  100000

In [63]:
# Basic DataFrame understanding

df.head()

      name  age  salary
0   biplob   23   34000
1      ram   80   70000
2     hari   40   50000
3  krishna   10  100000

In [64]:
df.tail(2)

      name  age  salary
2     hari   40   50000
3  krishna   10  100000

In [65]:
df.shape

(4, 3)

In [66]:
df.columns

Index(['name', 'age', 'salary'], dtype='str')

In [67]:
changed_df=df.rename(columns={"name":"Name","age":"Age","salary":"Montlhy_Salary"},inplace=True)

In [68]:
df

      Name  Age  Montlhy_Salary
0   biplob   23           34000
1      ram   80           70000
2     hari   40           50000
3  krishna   10          100000

In [69]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      str
 1   Age             4 non-null      int64
 2   Montlhy_Salary  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [70]:
df.describe()

             Age  Montlhy_Salary
count   4.000000        4.000000
mean   38.250000    63500.000000
std    30.423401    28442.925307
min    10.000000    34000.000000
25%    19.750000    46000.000000
50%    31.500000    60000.000000
75%    50.000000    77500.000000
max    80.000000   100000.000000

In [71]:
# Save and Load data from csv
df.to_csv('test_value.csv',index=False)

In [ ]:
load_df = pd.read_csv('test_value.csv')
load_df

      Name  Age  Montlhy_Salary
0   biplob   23           34000
1      ram   80           70000
2     hari   40           50000
3  krishna   10          100000