In [52]:
import pandas as pd

In [53]:
pd.__version__

'3.0.5'

In [54]:
# create Dataframe

df = pd.DataFrame([11,12,13],columns=['name'])
print(df)

   name
0    11
1    12
2    13

In [55]:
print(type(df))

<class 'pandas.DataFrame'>

In [56]:
data = {
    'name':['biplob','ram','hari','krishna'],
    'age':[23,80,40,10],
    'salary':[34000,70000,50000,100000]
}

In [57]:
df = pd.DataFrame(data)
print(df)

      name  age  salary
0   biplob   23   34000
1      ram   80   70000
2     hari   40   50000
3  krishna   10  100000

In [58]:
# Basic DataFrame understanding

df.head()

      name  age  salary
0   biplob   23   34000
1      ram   80   70000
2     hari   40   50000
3  krishna   10  100000

In [59]:
df.tail(2)

      name  age  salary
2     hari   40   50000
3  krishna   10  100000

In [60]:
df.shape

(4, 3)

In [61]:
df.columns

Index(['name', 'age', 'salary'], dtype='str')

In [62]:
changed_df=df.rename(columns={"name":"Name","age":"Age","salary":"Montlhy_Salary"},inplace=True)

In [63]:
df

      Name  Age  Montlhy_Salary
0   biplob   23           34000
1      ram   80           70000
2     hari   40           50000
3  krishna   10          100000

In [64]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      str
 1   Age             4 non-null      int64
 2   Montlhy_Salary  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [65]:
df.describe()

             Age  Montlhy_Salary
count   4.000000        4.000000
mean   38.250000    63500.000000
std    30.423401    28442.925307
min    10.000000    34000.000000
25%    19.750000    46000.000000
50%    31.500000    60000.000000
75%    50.000000    77500.000000
max    80.000000   100000.000000

In [66]:
# Save and Load data from csv
df.to_csv('test_value.csv',index=False)

In [67]:
load_df = pd.read_csv('test_value.csv')
load_df

      Name  Age  Montlhy_Salary
0   biplob   23           34000
1      ram   80           70000
2     hari   40           50000
3  krishna   10          100000

In [68]:
# select column

df[['Name']]

      Name
0   biplob
1      ram
2     hari
3  krishna

In [69]:
df[['Name','Age']]

      Name  Age
0   biplob   23
1      ram   80
2     hari   40
3  krishna   10

In [70]:
# select rows
# loc = indexx name baased
df.loc[df.Name=='biplob']
df.loc[(df.Name=='biplob') & (df.Montlhy_Salary >=40000)]

Empty DataFrame
Columns: [Name, Age, Montlhy_Salary]
Index: []

In [71]:
# iloc -- index value based
df.iloc[0:2]

     Name  Age  Montlhy_Salary
0  biplob   23           34000
1     ram   80           70000

In [72]:
# filter df
df

      Name  Age  Montlhy_Salary
0   biplob   23           34000
1      ram   80           70000
2     hari   40           50000
3  krishna   10          100000

In [73]:
df[(df['Age']>24) & (df['Montlhy_Salary']>=55000)]

  Name  Age  Montlhy_Salary
1  ram   80           70000

In [74]:
df.where(df['Age']>=25,other='Not Eligible')

           Name           Age Montlhy_Salary
0  Not Eligible  Not Eligible   Not Eligible
1           ram            80          70000
2          hari            40          50000
3  Not Eligible  Not Eligible   Not Eligible

In [75]:
df

      Name  Age  Montlhy_Salary
0   biplob   23           34000
1      ram   80           70000
2     hari   40           50000
3  krishna   10          100000

In [76]:
# add new column

df['Team']=['DA','HR','CTO','CEO']

In [77]:
df

      Name  Age  Montlhy_Salary Team
0   biplob   23           34000   DA
1      ram   80           70000   HR
2     hari   40           50000  CTO
3  krishna   10          100000  CEO

In [78]:
df['Bonus']= df['Montlhy_Salary']*0.2
df

      Name  Age  Montlhy_Salary Team    Bonus
0   biplob   23           34000   DA   6800.0
1      ram   80           70000   HR  14000.0
2     hari   40           50000  CTO  10000.0
3  krishna   10          100000  CEO  20000.0

In [79]:
# add new rows
df.loc[len(df)] =['Shiva','81','115000','chairman','25000']

In [80]:
df

      Name Age Montlhy_Salary      Team    Bonus
0   biplob  23          34000        DA   6800.0
1      ram  80          70000        HR  14000.0
2     hari  40          50000       CTO  10000.0
3  krishna  10         100000       CEO  20000.0
4    Shiva  81         115000  chairman    25000

In [81]:
len(df)

5

In [82]:
# update value
df.loc[3, 'Age'] = 50
df

      Name Age Montlhy_Salary      Team    Bonus
0   biplob  23          34000        DA   6800.0
1      ram  80          70000        HR  14000.0
2     hari  40          50000       CTO  10000.0
3  krishna  50         100000       CEO  20000.0
4    Shiva  81         115000  chairman    25000

In [83]:
# update value using column name

df.loc[df.Name =='ram','Age']=60

In [84]:
df

      Name Age Montlhy_Salary      Team    Bonus
0   biplob  23          34000        DA   6800.0
1      ram  60          70000        HR  14000.0
2     hari  40          50000       CTO  10000.0
3  krishna  50         100000       CEO  20000.0
4    Shiva  81         115000  chairman    25000

In [85]:
# delete value row and column values

df.drop(df[df.Name== 'biplob'].index,inplace=True) #drop row axis = 0

In [86]:
df.drop('Bonus',axis=1,inplace=True)

In [87]:
df

      Name Age Montlhy_Salary      Team
1      ram  60          70000        HR
2     hari  40          50000       CTO
3  krishna  50         100000       CEO
4    Shiva  81         115000  chairman

In [88]:
print(type(df['Age']))

<class 'pandas.Series'>

In [89]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 1 to 4
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      str
 1   Age             4 non-null      object
 2   Montlhy_Salary  4 non-null      object
 3   Team            4 non-null      str
dtypes: object(2), str(2)
memory usage: 260.0+ bytes

In [90]:
# Sorting value
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')

df = df.sort_values('Age', ascending=False)

In [91]:
df

      Name  Age Montlhy_Salary      Team
4    Shiva   81         115000  chairman
1      ram   60          70000        HR
3  krishna   50         100000       CEO
2     hari   40          50000       CTO

In [92]:
# Working with datetime values
df['DOJ']=['2023-01-01','2024-01-10','2024-02-12','2024-10-12']
df

      Name  Age Montlhy_Salary      Team         DOJ
4    Shiva   81         115000  chairman  2023-01-01
1      ram   60          70000        HR  2024-01-10
3  krishna   50         100000       CEO  2024-02-12
2     hari   40          50000       CTO  2024-10-12

In [93]:
df['DOJ'].dtype

In [94]:
df['DOJ'] = pd.to_datetime(df['DOJ'])

In [96]:
df.dtypes

Name                         str
Age                        int64
Montlhy_Salary            object
Team                         str
DOJ               datetime64[us]
dtype: object

In [97]:
df1=df['DOJ2']=['01-01-2023','12-01-2024','02-12-2024','18-02-2024']

In [102]:
df1=df

In [104]:
df1

      Name  Age Montlhy_Salary      Team        DOJ        DOJ2
4    Shiva   81         115000  chairman 2023-01-01  01-01-2023
1      ram   60          70000        HR 2024-01-10  12-01-2024
3  krishna   50         100000       CEO 2024-02-12  02-12-2024
2     hari   40          50000       CTO 2024-10-12  18-02-2024

In [106]:
df1['DOJ2'].dtypes

In [109]:
df1['DOJ2']=pd.to_datetime(df['DOJ2'],format='%d-%m-%Y')

In [110]:
df1['DOJ2'].dtypes

dtype('<M8[us]')

In [111]:
df1

      Name  Age Montlhy_Salary      Team        DOJ       DOJ2
4    Shiva   81         115000  chairman 2023-01-01 2023-01-01
1      ram   60          70000        HR 2024-01-10 2024-01-12
3  krishna   50         100000       CEO 2024-02-12 2024-12-02
2     hari   40          50000       CTO 2024-10-12 2024-02-18

In [114]:
df.drop('DOJ2',inplace=True,axis=1)
df

      Name  Age Montlhy_Salary      Team        DOJ
4    Shiva   81         115000  chairman 2023-01-01
1      ram   60          70000        HR 2024-01-10
3  krishna   50         100000       CEO 2024-02-12
2     hari   40          50000       CTO 2024-10-12

In [115]:
df['DOJ'].dt.year

4    2023
1    2024
3    2024
2    2024
Name: DOJ, dtype: int32

In [119]:
print('month:',df['DOJ'].dt.month)
print('day:',df['DOJ'].dt.day)

month: 4     1
1     1
3     2
2    10
Name: DOJ, dtype: int32
day: 4     1
1    10
3    12
2    12
Name: DOJ, dtype: int32